/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.swing.view;

// Sử dụng FlatLaf có sẵn
import com.formdev.flatlaf.FlatLightLaf;

import app.swing.view.panel.QuanLySanPhamView;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatClientProperties;
import javax.swing.UIManager;

/**
 *
 * @author khaim
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        addTab();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flatDarculaLaf1 = new com.formdev.flatlaf.FlatDarculaLaf();
        tbpnlMain = new javax.swing.JTabbedPane();
        pnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbpnlMain.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        tbpnlMain.addTab("Quản lý sản phẩm", pnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpnlMain)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(tbpnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set FlatLaf look and feel */
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());

            // Tùy biến tab
            UIManager.put("TabbedPane.selectedBackground", java.awt.Color.WHITE);
            UIManager.put("TabbedPane.background", new java.awt.Color(245, 245, 245));
            UIManager.put("TabbedPane.foreground", new java.awt.Color(60, 60, 60));
            UIManager.put("TabbedPane.selectedForeground", new java.awt.Color(0, 120, 215));
            UIManager.put("TabbedPane.tabInsets", new javax.swing.plaf.InsetsUIResource(10, 20, 10, 20));
            UIManager.put("TabbedPane.showTabSeparators", true);
            UIManager.put("TabbedPane.tabSeparatorColor", new java.awt.Color(220, 220, 220));
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
            ex.printStackTrace();

            // Fallback to system look and feel
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MainFrame frame = new MainFrame();
            // Sau khi initComponents()
            frame.tbpnlMain.putClientProperty(FlatClientProperties.TABBED_PANE_TAB_TYPE, "card");
            frame.tbpnlMain.putClientProperty(FlatClientProperties.TABBED_PANE_TAB_HEIGHT, 40);
            frame.tbpnlMain.putClientProperty(FlatClientProperties.TABBED_PANE_TAB_AREA_ALIGNMENT, "center");
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }

    public void addTab() {
        QuanLySanPhamView quanLySanPhamView = new QuanLySanPhamView();

        // Xóa layout cũ của panel
        pnl.removeAll();

        pnl.setLayout(new java.awt.BorderLayout());
        pnl.add(quanLySanPhamView, java.awt.BorderLayout.CENTER);

        quanLySanPhamView.setPreferredSize(null); // Let it calculate automatically

        // Refresh lại giao diện
        pnl.revalidate();
        pnl.repaint();

        // Force update size
        this.pack();
        this.setExtendedState(this.getExtendedState()); // Refresh window state
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.formdev.flatlaf.FlatDarculaLaf flatDarculaLaf1;
    private javax.swing.JPanel pnl;
    public javax.swing.JTabbedPane tbpnlMain;
    // End of variables declaration//GEN-END:variables
}
